name: generate animation

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
    - cron: "0 */12 * * *" # every 12 hours

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v1.1.2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
          author: rexlow <qiweilow950823@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
